# =========================
# APP
# =========================
spring.application.name=nutrition-sport-tracker

# =========================
# DATABASE (MySQL)
# =========================
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/beslenme_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Europe/Istanbul
spring.datasource.username=root
spring.datasource.password=12345678!

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# =========================
# TIMEZONE (Cron için önemli)
# =========================
spring.jackson.time-zone=Europe/Istanbul

# =========================
# MAIL (Gmail SMTP)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meralates2002@gmail.com
spring.mail.password=onsldhbvxxyvshzg
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =========================
# OPENROUTER (AI)
# =========================
openrouter.api.key=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
openrouter.model=openai/gpt-4o-mini
openrouter.temperature=0.6

# =========================
# JWT (tek tanesi kals?n)
# =========================
jwt.secret=FX8dI2Bayp1Wdiox7uezMuKDhQGzOzWglclefAIceRfjTw8lg5RrCUjSDCC1/DuWy5k6wj9C+u/r35NEc2ATng==
jwt.expiration=86400000

# =========================
# USDA
# =========================
usda.base-url=https://api.nal.usda.gov/fdc
usda.api.key=MfVffY3TBiaGfX3eeYqqoDBbNkPqnrqeFikSFyPa